name: dotfile testing
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'

jobs:
  run-on-macos:
    name: Run on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup stack
      uses: mstksg/setup-stack@v1
    - run: stack --version
